const constants = {
  FORM_SUBMIT: 'FORM_SUBMIT',
  FORM_INPUT: 'FORM_INPUT',
  TODO_TOGGLE: 'TODO_TOGGLE',
  TODO_DELETE: 'TODO_DELETE',
  TODO_START_EDITING: 'TODO_START_EDITING',
  TODO_DONE_EDITING: 'TODO_DONE_EDITING',
  TODO_CANCEL_EDITING: 'TODO_CANCEL_EDITING',
  ENTER_KEY: 13,
  ESCAPE_KEY: 27,
};

export default constants;
